### ISSUE TITLE
Is this how I would write a WinForms analyzer?

### ISSUE THREAD

**Issue by willibrandon** [RussKie/WindowsFormsAnalyzers#5]
And what are your thoughts on an analyzer that recognizes the changing of an access modifier of a control in a base form from private to protected?

I have developers that do it often, resulting in issues similar to the one described here: https://stackoverflow.com/questions/73269750/c-the-winform-designer-is-constantly-generating-setchildindex-codes-on-deri

Would this be, in your opinion, an appropriate use of a WinForms analyzer?

**Comment by RussKie** [comment]
The behaviour discussed in the SO is "by design", how else would you ensure the inherited controls have the correct tab order?

> Is this how I would write a WinForms analyzer?

I guess :) That was my first attempt at writing analyzers, and it seemed to have worked. 

> what are your thoughts on an analyzer that recognizes the changing of an access modifier of a control in a base form from private to protected?

_Personally_, I don't see much value in this. But YMMV :)

**Comment by willibrandon** [comment]
> The behaviour discussed in the SO is "by design", how else would you ensure the inherited controls have the correct tab order?

My scenario is slightly different, where the developer wants to set the value of a property of a private control on the base form from the derived form, so they change the control's access modifier from private to protected to do so. This results in the control's index changing from 0, to an index other than 0, when the derived form is then subsequently opened, and saved in the designer. This sometimes gets missed by the developer, and goes unnoticed until an employee eats some dog food, or a user sees it and reports it as a bug :(

**Comment by RussKie** [comment]
I'd handle such cases through code reviews and automated tests.

**Comment by willibrandon** [comment]
Thank you for your input.

**Comment by RussKie** [comment]
E.g., in a test you could create an instance of a form/user control and then enumerate all controls building a dictionary of tab orders. Then assert with something like Verify.

**Comment by RussKie** [comment]
> Thank you for your input.

No worries at all :)
